### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by byerc** [aries-data/aries-activity-surveygizmo-source#13]
Pagination is only partially implemented. The source currently just makes a repetitive call to the same endpoint which results in duplicate records.

**Comment by beckysteele** [comment]
Hi @byerc, can you update this open issue since you've worked on the pagination w/streams for Survey Gizmo?

**Comment by byerc** [comment]
Completed.

**Comment by beckysteele** [comment]
Thanks @byerc!
