### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by trong-le** [aries-data/aries-activity-surveygizmo-source#3]
- [ ] Readme doesn't have descriptions or where to find ID's or config parameters
- [x] Formatting of example and response looks wonky

**Comment by jlaneve** [comment]
I'm working on this. @benjamingregory I also noticed that the methods aren't listed - is that something we want to do? There are about 30 methods, each requiring different parameters.

**Comment by benjamingregory** [comment]
@jlaneve Yes - abstract out what parameters you can (e.g. if accountId is listed a necessary for every one) but at the very least (for now) there should be a list of the methods.

**Comment by benjamingregory** [comment]
@jlaneve Hold on - is this already taken care of in development?

**Comment by jlaneve** [comment]
Nope, I'm adding my changes to the development branch though.

**Comment by benjamingregory** [comment]
got it

**Comment by jlaneve** [comment]
Changes have been pushed to the development branch and added to the open pull request.
