### ISSUE TITLE
Allow array of survey_id to be passed into config

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-surveygizmo-source#8]
**Current Behavior**
Currently, the activity takes a single survey_id and passes it to the method. It is not possible to request multiple surveys simultaneously.

**Expected Behavior**
The user should be able to pass in survey_id values to the `survey_id` endpoint. The activity should expect an array and iterate through it calling the appropriate method.

**Comment by beckysteele** [comment]
@byerc I've moved this to In Progress since you've already addressed arrays of survey_id's in the config.  Update the status during your Zenhub review today.  Thanks!

**Comment by byerc** [comment]
Completed.

**Comment by beckysteele** [comment]
Thanks @byerc!
